apiVersion: storage.azure.crossplane.io/v1alpha3
kind: ContainerClass
metadata:
  name: container
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  # Azure containers read their credentials from an account. We reuse the
  # providerRef class field to specify which account to read.
  accountReference:
    name: account
  providerRef:
    name: account
  reclaimPolicy: Delete
  nameFormat: example-%s
