apiVersion: network.aws.crossplane.io/v1alpha3
kind: RouteTable
metadata:
  name: routetable
spec:
  ## must provide one of vpcIdRef and vpcId
  # vpcIdRef:
  #   name: sample-vpc
  # vpcId: my-vpc
  ## routes and associations can either be assigned using names or references
  # routes:
  #   - destinationCidrBlock: 0.0.0.0/0
  #     gatewayIdRef:
  #       name: sample-internetgateway
  # associations:
  #   - subnetIdRef:
  #       name: sample-subnet1
  #   - subnetIdRef:
  #       name: sample-subnet2
  #   - subnetIdRef:
  #       name: sample-subnet3
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
